# Generated by Django 5.0.4 on 2024-04-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('count', models.CharField(max_length=50)),
                ('fitness_classes', models.BooleanField(default=False)),
                ('workout_program', models.BooleanField(default=False)),
                ('certified_trainer', models.BooleanField(default=False)),
                ('health_assessment', models.BooleanField(default=False)),
                ('goal_setting', models.BooleanField(default=False)),
                ('nutrition_consultation', models.BooleanField(default=False)),
                ('registered_dietitian', models.BooleanField(default=False)),
            ],
        ),
    ]
